version: '3.8'

services:
  #zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 2. Broker de Kafka (Modificado para Red)
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092" # Puerto para clientes externos (PC 1 y PC 3)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      
#USA LA IP DEL ORDEANDOR DE CLASE
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://192.168.1.102:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 3. Nuestra EV_Central
  ev_central:
    image: evcharging-app:latest  # La imagen que construimos con el Dockerfile
    container_name: ev_central
    depends_on: [kafka]
    command: py /app/ev_central/EV_Central.py
    ports:
      - "8000:8000" # Expone el puerto de Sockets (8000) al PC 2
    volumes:
      # Monta el volumen para que la BBDD sea persistente
      - central_db_data:/app/ev_central/

# Definimos el volumen para la BBDD
volumes:
  central_db_data: